[package]
name = "futuresdr-burn"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
anyhow = "1.0"
burn = { version = "0.17", features = [
  "ndarray",
  "tui",
  "train",
  "wgpu",
  "webgpu",
  "autotune",
  "fusion",
] }
futuresdr = { path = "../..", features = ["burn", "seify", "soapy"] }
inplace = { path = "../inplace" }
log = "0.4"
ndarray = "0.16"
ndarray-npy = "0.9"
serde = { version = "1.0", features = ["derive"] }
