use std::future::Future;

use crate::runtime::dev::BlockInbox;
use crate::runtime::dev::BlockMeta;
use crate::runtime::dev::LocalWorkIo;
use crate::runtime::dev::MessageOutputs;
use crate::runtime::dev::WorkIo;
use futuresdr::runtime::BlockId;
use futuresdr::runtime::Error;
use futuresdr::runtime::Pmt;
use futuresdr::runtime::PortId;
use futuresdr::runtime::Result;
use futuresdr::runtime::buffer::BufferReader;

/// Send-capable proof for the internal block interface.
///
/// Block authors should implement [`crate::runtime::dev::Kernel`], not this
/// trait. `SendKernelInterface` is public only so downstream runtime internals
/// can name the send-capable proof of a generated [`KernelInterface`] impl.
#[doc(hidden)]
pub trait SendKernelInterface: KernelInterface + Send
where
    Self: KernelInterface<stream_ports_notify_finished(..): Send, call_handler(..): Send>,
{
}

impl<T> SendKernelInterface for T where
    T: KernelInterface<stream_ports_notify_finished(..): Send, call_handler(..): Send> + Send
{
}

/// Internal block interface generated by `#[derive(Block)]` and consumed by the
/// local runtime path.
///
/// It works with primary local buffer traits and does not require returned
/// futures or the kernel type to be `Send`.
#[doc(hidden)]
pub trait KernelInterface {
    /// If true, the block is run in a separate thread.
    fn is_blocking() -> bool;
    /// Name of the block.
    fn type_name() -> &'static str;
    /// Input Stream Ports.
    fn stream_inputs(&self) -> Vec<String>;
    /// Output Stream Ports.
    fn stream_outputs(&self) -> Vec<String>;
    /// Initialize Stream Ports.
    fn stream_ports_init(&mut self, block_id: BlockId, inbox: BlockInbox);
    /// Validate Stream Ports.
    fn stream_ports_validate(&self) -> Result<(), Error>;
    /// Mark stream input as finished.
    fn stream_input_finish(&mut self, port_id: PortId) -> Result<(), Error>;
    /// Tell adjacent blocks that we are done.
    fn stream_ports_notify_finished(&mut self) -> impl Future<Output = ()>;
    /// Get dyn reference to stream input.
    fn stream_input(&mut self, id: &PortId) -> Result<&mut dyn BufferReader, Error>;
    /// Connect dyn BufferReader by downcasting it.
    fn connect_stream_output(
        &mut self,
        id: &PortId,
        reader: &mut dyn BufferReader,
    ) -> Result<(), Error>;

    /// Input Message Handler Names.
    fn message_inputs() -> &'static [&'static str];
    /// Output Message Handler Names.
    fn message_outputs() -> &'static [&'static str];
    /// Call message handlers of the kernel.
    fn call_handler(
        &mut self,
        _io: &mut WorkIo,
        _mo: &mut MessageOutputs,
        _meta: &mut BlockMeta,
        id: PortId,
        _p: Pmt,
    ) -> impl Future<Output = Result<Pmt, Error>>;
}

/// Internal block interface generated by `#[derive(LocalBlock)]` and consumed
/// by local runtime paths.
#[doc(hidden)]
pub trait LocalKernelInterface {
    /// If true, the block is run in a separate thread.
    fn is_blocking() -> bool;
    /// Name of the block.
    fn type_name() -> &'static str;
    /// Input Stream Ports.
    fn stream_inputs(&self) -> Vec<String>;
    /// Output Stream Ports.
    fn stream_outputs(&self) -> Vec<String>;
    /// Initialize Stream Ports.
    fn stream_ports_init(&mut self, block_id: BlockId, inbox: BlockInbox);
    /// Validate Stream Ports.
    fn stream_ports_validate(&self) -> Result<(), Error>;
    /// Mark stream input as finished.
    fn stream_input_finish(&mut self, port_id: PortId) -> Result<(), Error>;
    /// Tell adjacent blocks that we are done.
    fn stream_ports_notify_finished(&mut self) -> impl Future<Output = ()>;
    /// Get dyn reference to stream input.
    fn stream_input(&mut self, id: &PortId) -> Result<&mut dyn BufferReader, Error>;
    /// Connect dyn BufferReader by downcasting it.
    fn connect_stream_output(
        &mut self,
        id: &PortId,
        reader: &mut dyn BufferReader,
    ) -> Result<(), Error>;

    /// Input Message Handler Names.
    fn message_inputs() -> &'static [&'static str];
    /// Output Message Handler Names.
    fn message_outputs() -> &'static [&'static str];
    /// Call message handlers of the local kernel.
    fn call_handler(
        &mut self,
        _io: &mut LocalWorkIo,
        _mo: &mut MessageOutputs,
        _meta: &mut BlockMeta,
        id: PortId,
        _p: Pmt,
    ) -> impl Future<Output = Result<Pmt, Error>>;
}

fn apply_local_work_io(local_io: &mut LocalWorkIo, work_io: WorkIo) {
    local_io.call_again = work_io.call_again;
    local_io.finished = work_io.finished;
    local_io.block_on = work_io
        .block_on
        .map(|f| f as std::pin::Pin<Box<dyn Future<Output = ()>>>);
}

impl<T> LocalKernelInterface for T
where
    T: KernelInterface,
{
    fn is_blocking() -> bool {
        <T as KernelInterface>::is_blocking()
    }

    fn type_name() -> &'static str {
        <T as KernelInterface>::type_name()
    }

    fn stream_inputs(&self) -> Vec<String> {
        <T as KernelInterface>::stream_inputs(self)
    }

    fn stream_outputs(&self) -> Vec<String> {
        <T as KernelInterface>::stream_outputs(self)
    }

    fn stream_ports_init(&mut self, block_id: BlockId, inbox: BlockInbox) {
        <T as KernelInterface>::stream_ports_init(self, block_id, inbox);
    }

    fn stream_ports_validate(&self) -> Result<(), Error> {
        <T as KernelInterface>::stream_ports_validate(self)
    }

    fn stream_input_finish(&mut self, port_id: PortId) -> Result<(), Error> {
        <T as KernelInterface>::stream_input_finish(self, port_id)
    }

    fn stream_ports_notify_finished(&mut self) -> impl Future<Output = ()> {
        <T as KernelInterface>::stream_ports_notify_finished(self)
    }

    fn stream_input(&mut self, id: &PortId) -> Result<&mut dyn BufferReader, Error> {
        <T as KernelInterface>::stream_input(self, id)
    }

    fn connect_stream_output(
        &mut self,
        id: &PortId,
        reader: &mut dyn BufferReader,
    ) -> Result<(), Error> {
        <T as KernelInterface>::connect_stream_output(self, id, reader)
    }

    fn message_inputs() -> &'static [&'static str] {
        <T as KernelInterface>::message_inputs()
    }

    fn message_outputs() -> &'static [&'static str] {
        <T as KernelInterface>::message_outputs()
    }

    async fn call_handler(
        &mut self,
        io: &mut LocalWorkIo,
        mo: &mut MessageOutputs,
        meta: &mut BlockMeta,
        id: PortId,
        p: Pmt,
    ) -> Result<Pmt, Error> {
        let mut work_io = WorkIo {
            call_again: io.call_again,
            finished: io.finished,
            block_on: None,
        };
        let result =
            <T as KernelInterface>::call_handler(self, &mut work_io, mo, meta, id, p).await;
        apply_local_work_io(io, work_io);
        result
    }
}
