[build]
target = "index.html"
dist = "dist"
filehash = false
release = true
public_url = "/examples/wlan/"

[serve.headers]
"Cross-Origin-Opener-Policy" = "same-origin"
"Cross-Origin-Embedder-Policy" = "require-corp"
