[package]
name = "rattlegram"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
rustfft = "6.1"
futuresdr = { path = "../..", features = ["seify"] }
